spring:
  kafka:
    bootstrap-servers: localhost:9092

    # Configurações globais para consumidores
    consumer:
      auto-offset-reset: earliest

    # Configurações específicas para o consumer de processamento de vídeos
    video-consumer:
      group-id: video-group
      topic: video-topic

    # Configurações específicas para o consumer de notificações por e-mail
    email-consumer:
      group-id: email-notification-group
      topic: video-status-topic

    # Configurações do producer (se necessário)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: project
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=public} # 1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true # 2
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 3
    properties:
      hibernate:
        globally_quoted_identifiers: true # 4
        show_sql: true
  main:
    allow-bean-definition-overriding: true
    logging:
      level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
        tech.fiap.hackaton: DEBUG

