apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default-namespace
spec:
  selector:
    app: hackaton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer